import React, { useState, useEffect } from 'react';

const QuizTakingInterface = ({ quizData, userAnswers, onAnswersUpdate, onSubmit, onBack }) => {
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [timeLeft, setTimeLeft] = useState(quizData.duration * 60);
  const [showSubmitConfirm, setShowSubmitConfirm] = useState(false);
  const [selectedSection, setSelectedSection] = useState(0);

  const currentSection = quizData.sections[selectedSection];
  const currentQuestion = currentSection?.questions[currentQuestionIndex];

  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft(prev => {
        if (prev <= 1) {
          handleAutoSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const handleAutoSubmit = () => {
    onSubmit(userAnswers, (quizData.duration * 60) - timeLeft);
  };

  const handleAnswerSelect = (answerIndex) => {
    const newAnswers = [...userAnswers];
    const globalIndex = getGlobalQuestionIndex();
    newAnswers[globalIndex] = answerIndex;
    onAnswersUpdate(newAnswers);
  };

  const handleNext = () => {
    if (currentQuestionIndex < currentSection.questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    } else if (selectedSection < quizData.sections.length - 1) {
      setSelectedSection(prev => prev + 1);
      setCurrentQuestionIndex(0);
    }
  };

  const handlePrev = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
    } else if (selectedSection > 0) {
      setSelectedSection(prev => prev - 1);
      setCurrentQuestionIndex(quizData.sections[selectedSection - 1].questions.length - 1);
    }
  };

  const handleQuestionNav = (sectionIndex, questionIndex) => {
    setSelectedSection(sectionIndex);
    setCurrentQuestionIndex(questionIndex);
  };

  const getGlobalQuestionIndex = () => {
    let globalIndex = 0;
    for (let i = 0; i < selectedSection; i++) {
      globalIndex += quizData.sections[i].questions.length;
    }
    return globalIndex + currentQuestionIndex;
  };

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const answeredCount = userAnswers.filter(answer => answer !== null && answer !== undefined).length;
  const totalQuestions = quizData.sections.reduce((total, section) => total + section.questions.length, 0);

  const getQuestionStatus = (sectionIndex, questionIndex) => {
    let globalIndex = 0;
    for (let i = 0; i < sectionIndex; i++) {
      globalIndex += quizData.sections[i].questions.length;
    }
    globalIndex += questionIndex;
    return userAnswers[globalIndex];
  };

  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-100 min-h-screen py-8">

      <div className="max-w-7xl mx-auto">
      {/* Quiz Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between mb-6 p-6 bg-white rounded-2xl shadow-lg border">
        <div className="flex-1">
          <h2 className="text-2xl font-bold text-gray-900">{quizData.title}</h2>
          <p className="text-gray-600">AI-Generated by verve.io</p>
        </div>
        <div className="flex items-center space-x-4 mt-4 lg:mt-0">
          <div className={`text-2xl font-bold ${timeLeft < 300 ? 'text-red-600' : 'text-gray-900'}`}>
            {formatTime(timeLeft)}
          </div>
          <button
            onClick={() => setShowSubmitConfirm(true)}
            className="px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-xl font-semibold hover:from-green-700 hover:to-emerald-700 transition-all shadow-lg"
          >
            Submit to AI Analysis
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Main Question Area */}
        <div className="lg:col-span-3">
          <div className="bg-white rounded-2xl shadow-lg border p-6">
            {/* Section Header */}
            <div className="flex items-center justify-between mb-6 pb-4 border-b">
              <div>
                <h3 className="text-xl font-bold text-gray-900">{currentSection.name}</h3>
                <p className="text-gray-600 text-sm">{currentSection.instructions}</p>
              </div>
              <div className="text-sm text-gray-500">
                Question {currentQuestionIndex + 1} of {currentSection.questions.length} in this section
              </div>
            </div>

            {/* Question Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center space-x-4">
                <div className="bg-blue-600 text-white px-4 py-2 rounded-xl font-bold">
                  Q{currentQuestionIndex + 1}
                </div>
                <div className="text-sm text-gray-600 bg-gray-100 px-3 py-1 rounded-full capitalize">
                  {currentQuestion.difficulty}
                </div>
                <div className="text-sm text-gray-600 bg-blue-100 px-3 py-1 rounded-full">
                  {currentQuestion.topic}
                </div>
              </div>
              <div className="text-sm text-gray-500">
                Suggested time: {Math.round(currentQuestion.timeEstimate / 60)} min
              </div>
            </div>

            {/* Question Text */}
            <div className="mb-8">
              <h3 className="text-lg font-semibold text-gray-900 leading-relaxed">
                {currentQuestion.text}
              </h3>
            </div>

            {/* Options */}
            <div className="space-y-4">
              {currentQuestion.options.map((option, index) => (
                <div
                  key={index}
                  className={`p-4 border-2 rounded-xl cursor-pointer transition-all ${
                    userAnswers[getGlobalQuestionIndex()] === index
                      ? 'border-blue-500 bg-blue-50 shadow-md'
                      : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                  }`}
                  onClick={() => handleAnswerSelect(index)}
                >
                  <div className="flex items-center">
                    <div className={`w-10 h-10 rounded-lg flex items-center justify-center mr-4 font-semibold ${
                      userAnswers[getGlobalQuestionIndex()] === index
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-200 text-gray-700'
                    }`}>
                      {String.fromCharCode(65 + index)}
                    </div>
                    <span className="text-gray-900 text-lg">{option}</span>
                  </div>
                </div>
              ))}
            </div>

            {/* Navigation Buttons */}
            <div className="flex justify-between mt-8 pt-6 border-t">
              <button
                onClick={handlePrev}
                disabled={currentQuestionIndex === 0 && selectedSection === 0}
                className="px-6 py-3 border border-gray-300 text-gray-700 rounded-xl font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50 transition-colors"
              >
                <i className="fas fa-arrow-left mr-2"></i>
                Previous
              </button>
              
              <button
                onClick={handleNext}
                disabled={currentQuestionIndex === currentSection.questions.length - 1 && selectedSection === quizData.sections.length - 1}
                className="px-6 py-3 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-xl font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:from-blue-700 hover:to-cyan-700 transition-all shadow-lg"
              >
                {currentQuestionIndex === currentSection.questions.length - 1 && selectedSection === quizData.sections.length - 1 ? 'Last Question' : 'Next'}
                <i className="fas fa-arrow-right ml-2"></i>
              </button>
            </div>
          </div>
        </div>

        {/* Sidebar - Navigation */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-2xl shadow-lg border p-6 sticky top-4">
            {/* Section Tabs */}
            <div className="mb-4">
              <h4 className="font-semibold text-gray-900 mb-3">Sections</h4>
              <div className="flex flex-wrap gap-2">
                {quizData.sections.map((section, index) => (
                  <button
                    key={index}
                    onClick={() => {
                      setSelectedSection(index);
                      setCurrentQuestionIndex(0);
                    }}
                    className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${
                      selectedSection === index
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                    }`}
                  >
                    {section.name}
                  </button>
                ))}
              </div>
            </div>

            {/* Questions Grid */}
            <h4 className="font-semibold text-gray-900 mb-3">Questions</h4>
            <div className="grid grid-cols-4 gap-2 mb-6">
              {currentSection.questions.map((_, index) => (
                <button
                  key={index}
                  onClick={() => handleQuestionNav(selectedSection, index)}
                  className={`w-10 h-10 rounded-lg flex items-center justify-center text-sm font-medium transition-all ${
                    currentQuestionIndex === index
                      ? 'bg-blue-600 text-white'
                      : getQuestionStatus(selectedSection, index) !== null && getQuestionStatus(selectedSection, index) !== undefined
                      ? 'bg-green-500 text-white'
                      : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }`}
                >
                  {index + 1}
                </button>
              ))}
            </div>
            
            {/* Progress */}
            <div className="p-4 bg-gray-50 rounded-xl">
              <div className="flex justify-between text-sm mb-2">
                <span className="text-gray-600">Progress</span>
                <span className="font-semibold">{answeredCount}/{totalQuestions}</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div 
                  className="bg-green-500 h-2 rounded-full transition-all"
                  style={{ width: `${(answeredCount / totalQuestions) * 100}%` }}
                ></div>
              </div>
              <div className="flex justify-between text-xs text-gray-500 mt-2">
                <span>Answered: {answeredCount}</span>
                <span>Remaining: {totalQuestions - answeredCount}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Submit Confirmation Modal */}
      {showSubmitConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl p-6 max-w-md w-full">
            <div className="text-center mb-6">
              <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <i className="fas fa-robot text-blue-600 text-2xl"></i>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">Submit to verve.io?</h3>
              <p className="text-gray-600">
                Your quiz will be analyzed by verve.io for detailed performance insights.
              </p>
              <p className="text-orange-600 font-semibold mt-2">
                {answeredCount < totalQuestions && 
                  `You have ${totalQuestions - answeredCount} unanswered questions.`
                }
              </p>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => setShowSubmitConfirm(false)}
                className="flex-1 py-3 border border-gray-300 text-gray-700 rounded-xl font-semibold hover:bg-gray-50 transition-colors"
              >
                Continue
              </button>
              <button
                onClick={() => {
                  setShowSubmitConfirm(false);
                  onSubmit(userAnswers, (quizData.duration * 60) - timeLeft);
                }}
                className="flex-1 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-xl font-semibold hover:from-green-700 hover:to-emerald-700 transition-all"
              >
                Submit to AI
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
    </div>
  );
};

export default QuizTakingInterface;